# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tableformom.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from excel import *
from exConsts import *
from PyQt5.QtWidgets import QMessageBox
from openpyxl import Workbook, load_workbook
from openpyxl.utils import get_column_letter

class Ui_ProfileWindow(object):
    def setupUi(self, ProfileWindow):
        ProfileWindow.setObjectName("ProfileWindow")
        ProfileWindow.resize(350, 425)
        ProfileWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(ProfileWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 325, 71))
        self.label.setObjectName("label")
        self.PatientNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.PatientNameLabel.setGeometry(QtCore.QRect(20, 110, 51, 31))
        self.PatientNameLabel.setObjectName("PatientNameLabel")
        self.PatientNameValue = QtWidgets.QLabel(self.centralwidget)
        self.PatientNameValue.setGeometry(QtCore.QRect(80, 115, 100, 21))
        self.PatientNameValue.setObjectName("PatientNameValue")
        self.PayPerSessionLabel = QtWidgets.QLabel(self.centralwidget)
        self.PayPerSessionLabel.setGeometry(QtCore.QRect(20, 150, 141, 31))
        self.PayPerSessionLabel.setObjectName("PayPerSessionLabel")
        self.PayPerSessionValue = QtWidgets.QLabel(self.centralwidget)
        self.PayPerSessionValue.setGeometry(QtCore.QRect(170, 150, 51, 31))
        self.PayPerSessionValue.setObjectName("PayPerSessionValue")
        self.MonthListbox = QtWidgets.QComboBox(self.centralwidget)
        self.MonthListbox.setGeometry(QtCore.QRect(150, 300, 100, 21))
        self.MonthListbox.setObjectName("MonthListbox")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.MonthListbox.addItem("")
        self.PaymentLabel = QtWidgets.QLabel(self.centralwidget)
        self.PaymentLabel.setGeometry(QtCore.QRect(20, 260, 91, 31))
        self.PaymentLabel.setObjectName("PaymentLabel")
        self.PaymentInputbox = QtWidgets.QLineEdit(self.centralwidget)
        self.PaymentInputbox.setGeometry(QtCore.QRect(20, 300, 113, 22))
        self.PaymentInputbox.setObjectName("PaymentInputbox")
        self.PaymentButton = QtWidgets.QPushButton(self.centralwidget)
        self.PaymentButton.setGeometry(QtCore.QRect(20, 340, 80, 20))
        self.PaymentButton.setObjectName("PaymentButton")
        self.TotalPaymentLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalPaymentLabel.setGeometry(QtCore.QRect(20, 190, 141, 31))
        self.TotalPaymentLabel.setObjectName("TotalPaymentLabel")
        self.TotalPaymentValue = QtWidgets.QLabel(self.centralwidget)
        self.TotalPaymentValue.setGeometry(QtCore.QRect(120, 190, 100, 31))
        self.TotalPaymentValue.setObjectName("TotalPaymentValue")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 230, 325, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        ProfileWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProfileWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 291, 22))
        self.menubar.setObjectName("menubar")
        ProfileWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProfileWindow)
        self.statusbar.setObjectName("statusbar")
        ProfileWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProfileWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfileWindow)
        self.PaymentButton.clicked.connect(self.AddPayment)


    def AddPayment(self):
        Patname = str(self.PatientNameValue.text())
        if not str(self.PaymentInputbox.text()).isnumeric() or str(self.PaymentInputbox.text()) is None:
            msg = QMessageBox()
            msg.setIcon(msg.Information)
            msg.setWindowTitle("Erro!")
            msg.setText("O pagamento adicionado é inválido.")
            msg.exec()

        PaidValue = int(self.PaymentInputbox.text())
        Month = str(self.MonthListbox.currentText())

        IncrementPayment(Patname, PaidValue, Month, FILENAME)
        msg = QMessageBox()
        msg.setIcon(msg.Information)
        msg.setWindowTitle("Sucesso!")
        msg.setText("Pagamento incrementado com sucesso.")
        msg.exec()
        
    def retranslateUi(self, ProfileWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfileWindow.setWindowTitle(_translate("ProfileWindow", "Perfil do Paciente"))
        self.label.setText(_translate("ProfileWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">PERFIL DO PACIENTE</span></p></body></html>"))
        self.PatientNameLabel.setText(_translate("ProfileWindow", "NOME:"))
        self.PayPerSessionLabel.setText(_translate("ProfileWindow", "VALOR POR SESSÃO:"))
        self.MonthListbox.setItemText(0, _translate("ProfileWindow", "Janeiro"))
        self.MonthListbox.setItemText(1, _translate("ProfileWindow", "Fevereiro"))
        self.MonthListbox.setItemText(2, _translate("ProfileWindow", "Março"))
        self.MonthListbox.setItemText(3, _translate("ProfileWindow", "Abril"))
        self.MonthListbox.setItemText(4, _translate("ProfileWindow", "Maio"))
        self.MonthListbox.setItemText(5, _translate("ProfileWindow", "Junho"))
        self.MonthListbox.setItemText(6, _translate("ProfileWindow", "Julho"))
        self.MonthListbox.setItemText(7, _translate("ProfileWindow", "Agosto"))
        self.MonthListbox.setItemText(8, _translate("ProfileWindow", "Setembro"))
        self.MonthListbox.setItemText(9, _translate("ProfileWindow", "Outubro"))
        self.MonthListbox.setItemText(10, _translate("ProfileWindow", "Novembro"))
        self.MonthListbox.setItemText(11, _translate("ProfileWindow", "Dezembro"))
        self.PaymentLabel.setText(_translate("ProfileWindow", "PAGAMENTO:"))
        self.PaymentButton.setText(_translate("ProfileWindow", "Enviar"))
        self.TotalPaymentLabel.setText(_translate("ProfileWindow", "TOTAL PAGO:"))

    def FillContent(self, name, paypersession, totalpaid):
        self.PatientNameValue.setText(str(name))
        self.PayPerSessionValue.setText("R$ {}".format(str(paypersession)))
        self.TotalPaymentValue.setText("R$ {}".format(str(totalpaid)))

class Ui_PatientSearch(object):
    def setupUi(self, PatientSearch):
        PatientSearch.setObjectName("PatientSearch")
        PatientSearch.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(PatientSearch)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchPatientInputbox = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchPatientInputbox.setGeometry(QtCore.QRect(250, 130, 171, 31))
        self.SearchPatientInputbox.setObjectName("SearchPatientInputbox")
        self.SearchPatButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchPatButton.setGeometry(QtCore.QRect(440, 130, 81, 31))
        self.SearchPatButton.setObjectName("SearchPatButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 130, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 761, 71))
        self.label_2.setObjectName("label_2")
        self.PatTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.PatTableWidget.setGeometry(QtCore.QRect(100, 200, 601, 291))
        self.PatTableWidget.setObjectName("PatTableWidget")
        self.PatTableWidget.setColumnCount(4)
        self.PatTableWidget.setColumnWidth(0, 50)
        self.PatTableWidget.setColumnWidth(1, 200)
        self.PatTableWidget.setColumnWidth(2, 225)
        self.PatTableWidget.setColumnWidth(3,150)
        self.PatTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.PatTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PatTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PatTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.PatTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.PatTableWidget.setHorizontalHeaderItem(4, item)
        PatientSearch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PatientSearch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        PatientSearch.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PatientSearch)
        self.statusbar.setObjectName("statusbar")
        PatientSearch.setStatusBar(self.statusbar)

        self.retranslateUiforSearchPatient(PatientSearch)
        QtCore.QMetaObject.connectSlotsByName(PatientSearch)
        self.SearchPatButton.clicked.connect(self.LoadData)
        self.PatTableWidget.cellDoubleClicked.connect(self.OpenProfileWindow)

    def retranslateUiforSearchPatient(self, PatientSearch):
        _translate = QtCore.QCoreApplication.translate
        PatientSearch.setWindowTitle(_translate("PatientSearch", "Buscar Paciente"))
        self.SearchPatButton.setText(_translate("PatientSearch", "Buscar"))
        self.label.setText(_translate("PatientSearch", "<html><head/><body><p><span style=\" font-size:18pt;\">Nome:</span></p></body></html>"))
        self.label_2.setText(_translate("PatientSearch", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">BUSCAR PACIENTE</span></p></body></html>"))
        item = self.PatTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PatientSearch", "CEL"))
        item = self.PatTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PatientSearch", "NOME"))
        item = self.PatTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("PatientSearch", "VALOR POR SESSÃO"))
        item = self.PatTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("PatientSearch", "VALOR PAGO"))

    def OpenProfileWindow(self):
        wb = load_workbook(FILENAME, data_only=True)
        Row = self.PatTableWidget.currentRow()
        Column = 0
        print(Row, Column)
        XlCell = str(self.PatTableWidget.item(Row, Column).text())
        print(XlCell)
        Patient = SearchPatientByCell(XlCell, wb)

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ProfileWindow()
        self.ui.setupUi(self.window)
        self.ui.FillContent(name=Patient['name'], paypersession=Patient['PayPerSession'], totalpaid=Patient['TotalPayment'])
        self.window.show()





    def LoadData(self):
        self.PatTableWidget.clearContents()
        wb = load_workbook(FILENAME, data_only=True)
        Patname = str(self.SearchPatientInputbox.text())
        PossibleCells = SearchPatientByName(Patname, wb)
        if len(PossibleCells) == 0:
            msg = QMessageBox()
            msg.setIcon(msg.Information)
            msg.setWindowTitle("Erro!")
            msg.setText("Não há nenhum paciente com esse nome ou semelhante.")
            msg.exec()

            

        Patients = []
        for Cell in PossibleCells:
            print(Cell)
            Patients.append(GetPatientInformation(Cell, wb))

        row=0
        self.PatTableWidget.setRowCount(len(Patients))
        for Patient in Patients:
            self.PatTableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(Patient["cell"])))
            self.PatTableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(Patient["Name"])))
            self.PatTableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(Patient["PayPerSession"])))
            self.PatTableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str(Patient["TotalPayment"])))
            row+=1




class Ui_NewPatientWindow(object):
    def setupUi(self, NewPatientWindow):
        NewPatientWindow.setObjectName("NewPatientWindow")
        NewPatientWindow.resize(289, 459)
        self.centralwidget = QtWidgets.QWidget(NewPatientWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PaidSessionLabel = QtWidgets.QLabel(self.centralwidget)
        self.PaidSessionLabel.setGeometry(QtCore.QRect(60, 280, 151, 16))
        self.PaidSessionLabel.setObjectName("PaidSessionLabel")
        self.PaidSessionInputbox = QtWidgets.QLineEdit(self.centralwidget)
        self.PaidSessionInputbox.setGeometry(QtCore.QRect(60, 310, 161, 22))
        self.PaidSessionInputbox.setObjectName("PaidSessionInputbox")
        self.NameInputbox = QtWidgets.QLineEdit(self.centralwidget)
        self.NameInputbox.setGeometry(QtCore.QRect(60, 210, 161, 22))
        self.NameInputbox.setObjectName("NameInputbox")
        self.NameLabel = QtWidgets.QLabel(self.centralwidget)
        self.NameLabel.setGeometry(QtCore.QRect(60, 180, 71, 16))
        self.NameLabel.setObjectName("NameLabel")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(100, 360, 61, 31))
        self.SendButton.setObjectName("SendButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 241, 71))
        self.label.setObjectName("label")
        NewPatientWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NewPatientWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 289, 22))
        self.menubar.setObjectName("menubar")
        NewPatientWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NewPatientWindow)
        self.statusbar.setObjectName("statusbar")
        NewPatientWindow.setStatusBar(self.statusbar)

        self.retranslateUiForNewPatient(NewPatientWindow)
        QtCore.QMetaObject.connectSlotsByName(NewPatientWindow)
        self.SendButton.clicked.connect(self.AddPatient)

    def retranslateUiForNewPatient(self, NewPatientWindow):
        _translate = QtCore.QCoreApplication.translate
        NewPatientWindow.setWindowTitle(_translate("NewPatientWindow", "MainWindow"))
        self.PaidSessionLabel.setText(_translate("NewPatientWindow", "Valor por sessão:"))
        self.NameLabel.setText(_translate("NewPatientWindow", "Nome:"))
        self.SendButton.setText(_translate("NewPatientWindow", "Enviar"))
        self.label.setText(_translate("NewPatientWindow","<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">NOVO PACIENTE</span></p></body></html>"))

    def AddPatient(self):
        Patname = str(self.NameInputbox.text())
        value = float(self.PaidSessionInputbox.text())
        InsertPatient(Patname, value, FILENAME)
        msg = QMessageBox()
        msg.setIcon(msg.Information)
        msg.setWindowTitle("Success!")
        msg.setText("Paciente Adicionado.")
        msg.exec()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(619, 188)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 350, 51))
        self.label.setObjectName("label")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(40, 110, 141, 31))
        self.AddButton.setObjectName("AddButton")
        self.LeaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.LeaveButton.setGeometry(QtCore.QRect(440, 110, 141, 31))
        self.LeaveButton.setObjectName("LeaveButton")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(230, 110, 141, 31))
        self.SearchButton.setObjectName("SearchButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 619, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.LeaveButton.clicked.connect(MainWindow.close)
        self.AddButton.clicked.connect(self.CallNewPatientWindow)
        self.SearchButton.clicked.connect(self.CallPatientSearchWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">TABELA DE PACIENTES</span></p><p align=\"center\"><span style=\" font-size:9pt; font-style:italic;\">Feito por J. V. L. Alves</span></p></body></html>"))
        self.AddButton.setText(_translate("MainWindow", "Adicionar Paciente"))
        self.LeaveButton.setText(_translate("MainWindow", "Sair"))
        self.SearchButton.setText(_translate("MainWindow", "Procurar Paciente"))

    def CallNewPatientWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_NewPatientWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def CallPatientSearchWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PatientSearch()
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    principal = QtWidgets.QMainWindow()
    ui = Ui_MainWindow() #nome da classe
    ui.setupUi(principal)
    principal.show()
    sys.exit(app.exec_())