# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArknightsApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from app.Arkcrawler.cmd import mainrunning as mr
from app.Arkcrawler.cmd import *



class Ui_ArknightsApp(object):
    def setupUi(self, ArknightsApp):
        ArknightsApp.setObjectName("ArknightsApp")
        ArknightsApp.resize(597, 256)
        self.centralwidget = QtWidgets.QWidget(ArknightsApp)
        self.centralwidget.setObjectName("centralwidget")
        self.GetLatestNewsObj = QtWidgets.QPushButton(self.centralwidget)
        self.GetLatestNewsObj.setGeometry(QtCore.QRect(30, 210, 121, 26))
        self.GetLatestNewsObj.setObjectName("GetLatestNewsObj")
        self.GetEventsNewsObj = QtWidgets.QPushButton(self.centralwidget)
        self.GetEventsNewsObj.setGeometry(QtCore.QRect(30, 130, 121, 26))
        self.GetEventsNewsObj.setObjectName("GetEventsNewsObj")
        self.GetContestNewsObj = QtWidgets.QPushButton(self.centralwidget)
        self.GetContestNewsObj.setGeometry(QtCore.QRect(30, 170, 121, 26))
        self.GetContestNewsObj.setObjectName("GetContestNewsObj")
        self.SingleNewsCheckboxObj = QtWidgets.QCheckBox(self.centralwidget)
        self.SingleNewsCheckboxObj.setGeometry(QtCore.QRect(190, 130, 101, 21))
        self.SingleNewsCheckboxObj.setObjectName("SingleNewsCheckboxObj")
        self.AllNewsCheckboxObj = QtWidgets.QCheckBox(self.centralwidget)
        self.AllNewsCheckboxObj.setGeometry(QtCore.QRect(300, 130, 85, 21))
        self.AllNewsCheckboxObj.setObjectName("AllNewsCheckboxObj")
        self.AppTitle = QtWidgets.QLabel(self.centralwidget)
        self.AppTitle.setGeometry(QtCore.QRect(30, 20, 501, 41))
        self.AppTitle.setObjectName("AppTitle")
        self.LeaveButtonObj = QtWidgets.QPushButton(self.centralwidget)
        self.LeaveButtonObj.setGeometry(QtCore.QRect(490, 210, 71, 26))
        self.LeaveButtonObj.setObjectName("LeaveButtonObj")
        ArknightsApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(ArknightsApp)
        self.LeaveButtonObj.clicked.connect(ArknightsApp.close)
        QtCore.QMetaObject.connectSlotsByName(ArknightsApp)
        self.GetLatestNewsObj.clicked.connect(self.getLNews)

    def getLNews(self):
        mr.getLatestNews()
        msg = QMessageBox()
        msg.setIcon(msg.Information)
        msg.setWindowTitle("Success!")
        msg.setText("Downloading Latest News")
        msg.exec()

    def retranslateUi(self, ArknightsApp):
        _translate = QtCore.QCoreApplication.translate
        ArknightsApp.setWindowTitle(_translate("ArknightsApp", "MainWindow"))
        self.GetLatestNewsObj.setText(_translate("ArknightsApp", "Get Latest News"))
        self.GetEventsNewsObj.setText(_translate("ArknightsApp", "Get Event News"))
        self.GetContestNewsObj.setText(_translate("ArknightsApp", "Get Contest News"))
        self.SingleNewsCheckboxObj.setText(_translate("ArknightsApp", "Single News"))
        self.AllNewsCheckboxObj.setText(_translate("ArknightsApp", "All News"))
        self.AppTitle.setText(_translate("ArknightsApp", "<html><head/><body><p><img src=\":/Icon/Captura de Tela 2021-12-11 às 19.20.54.jpeg\"/><span style=\" font-size:24pt; font-weight:600;\">    ARKNIGHTS NEWS COLLECTOR</span></p><p><br/></p></body></html>"))
        self.LeaveButtonObj.setText(_translate("ArknightsApp", "Leave"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    principal = QtWidgets.QMainWindow()
    ui = Ui_ArknightsApp() #nome da classe
    ui.setupUi(principal)
    principal.show()
    sys.exit(app.exec_())

